version: 2
jobs:
  build:
    working_directory: ~/workspace 
    docker:
      - image: node:9.4.0
    steps:
      - checkout
      - restore_cache: 
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Check dist
          command: ls -la dist
      - run:
          name: Install firebase tools
          command: npm install -g firebase-tools
      - run:
          name: Deployment
          command: firebase deploy --project=$FIREBASE_PJ_RELEASE --token=$FIREBASE_TOKEN --non-interactive  
      - save_cache: 
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
